nais/naiserator

- api/types/v1alpha1/application.go
Refs #2. The structs are based on the code in `naisd`. YAML has been replaced with JSON, and all the fields have corresponding json annotations. Fasit, Redis, and Alerts have been removed.
> Import nais manifest spec from naisd code

- naiserator.go
- pkg/apis/naiserator/v1alpha1/defaults.go
- pkg/apis/naiserator/v1alpha1/types.go
- pkg/resourcecreator/resourcecreator.go
- pkg/resourcecreator/resourcecreator_test.go
This patch introduces a few changes:
* The behavior for `add` and `update` on resources are merged into one.
* `TypeMeta` is removed from the Application hashing function because the contents were inconsistent. @jhrv is this okay?
The result should be that Naiserator does not do needless syncing of existing resources.
> Merge add, update, and synchronize

- pkg/resourcecreator/ingress.go
The application does not need a prometheus enabled endpoint for
black box scraptng.
Only a readyness endpoint, which is mandatory.
This reverts commit 207b2e43be959b51aa7c30e115152bd994c18029.
> Scrape ingress regardless

- pkg/resourcecreator/certificateauthority.go
- pkg/resourcecreator/deployment.go
- pkg/resourcecreator/deployment_test.go
A system-wide certificate authority bundle will be mounted in from a ConfigMap, and replaces the following files in the container:
* /etc/ssl/certs/ca-certificates.crt
* /etc/pki/tls/certs/ca-bundle.crt
* /etc/ssl/ca-bundle.pem
* /etc/pki/tls/cacert.pem
* /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
In addition, a Java truststore file will be mounted to `/etc/ssl/certs/java/cacerts`, and its location and password made available through the environment variables `NAV_TRUSTSTORE_PATH` and `NAV_TRUSTSTORE_PASSWORD`.
> Inject certificate authority bundles as PEM and JKS to well-known locations

- pkg/apis/naiserator/v1alpha1/application.yaml
- pkg/apis/naiserator/v1alpha1/types.go
- pkg/resourcecreator/deployment.go
- pkg/resourcecreator/deployment_test.go
When setting up an `nais.io/Application` for kafka-connect I discovered that its only possible to use `value` in the `spec.env` map. kafka-connect needs the pod ip as an env variable that it will communicate to the other nodes in the kafka-connect cluster.
This can be solved by supporting `valueFrom.fieldRef.fieldPath`.
One caveat with this change is that we no longer require `value`, so if both `value` and `valueFrom` is missing the deployment will fail. Its not possible to use `oneOf` in the OpenAPI spec implemented in k8s: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/
> The following fields are removed as they aren’t supported by OpenAPI v2 (in future versions OpenAPI v3 will be used without these restrictions)
> The fields oneOf, …
> Add support for env var sources

- pkg/resourcecreator/istio.go
- pkg/resourcecreator/istio_test.go
Corrected some implementations on ServiceRole and ServiceRoleBinding:
- ServiceRole and -Binding now throws error if `Spec.AccessPolicy.Ingress.AllowAll` is set to true while there is defined access policy ingress rules.
- The created subjects of ServiceRoleBinding has the namespace defined in the rule, if set.
- The subject of ServiceRoleBinding is set to * if `allowAll` is true.
> Wrote tests for istio rbac

- pkg/apis/naiserator/v1alpha1/types.go
- pkg/resourcecreator/deployment.go
When the `Application` resource is annotated with the `kubernetes.io/change-cause` annotation, it would be nice to annotate the deployment resource as well. Annotating the deployment resource does not create a new replicaset.
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#checking-rollout-history-of-a-deployment
> Pass rollout reason annotation to deployment

- pkg/resourcecreator/istio.go
- pkg/resourcecreator/istio_test.go
- pkg/resourcecreator/networkpolicy.go
- pkg/resourcecreator/networkpolicy_test.go
- pkg/resourcecreator/resourcecreator.go
- pkg/resourcecreator/resourcecreator_test.go
- pkg/resourcecreator/virtualservice.go
This patch makes sure that `ServiceRole`, `ServiceRoleBinding`, `VirtualService` and `NetworkPolicy` objects implement the functionality required to have a working Ingress.
> Support Ingress-like behavior with access policies turned on

- README.md
- examples/nais-max.yaml
- examples/nais.yaml
- pkg/apis/naiserator/v1alpha1/meta.go
- pkg/apis/rbac.istio.io/v1alpha1/types.go
- pkg/resourcecreator/istio.go
- pkg/resourcecreator/istio_test.go
- pkg/resourcecreator/resourcecreator.go
Tok litt tid å komme igang. Og det ble litt flere endringer enn jeg orginalt så for meg. 
Det jeg i bunn og grunn har gjort er å bygge på ServiceRole og ServiceRoleBinding med to nye funksjoner ServiceRolePrometheus og ServiceRoleBindingPrometheus.
Foruten de lange funksjonsnavnene så gjør bare funksjonene små endringer på de allerede genererte structene, så om noe forandres i de underliggende funksjonene skal det gå fint. 
Siste ting, så la jeg også til Paths i AccessRule structet, så det er mulig å kontrollere paths.
Feedback og kritikk er veldig velkommen!
> Restrict prometheus

- naiserator.go
Brukte en del tid på å reprodusere issuen utifra beskrivelsen.
Det som skal til for at issuen blir triggret er at man går fra mer enn 0 Ingresser til 0. Da vil ingressene forbli, før denne forandringen.
Det denne endringen gjør er at den legger til 1 funksjon 'removeOrphanIngresses' som sjekker om det er 0 ingresser i app speccet som blir sendt inn og da prøver den å slette gamle ingresser assosiert med appen.
**Det er alikevel flere viktige ting å merke seg, som vi må gjøre før merge.**
Det er ingen automatiske tester av denne funksjonaliteten, fordi det krever en form for mocking. Dette er noe vi virkelig burde se på.
Den andre tingen, slik jeg har forstått det er at folk som har kommet over fra naisd til naiserator og ikke har spesifisert Ingresses eksplisitt men fortsatt lever på …
> Delete ingress object

- pkg/apis/nais.io/v1alpha1/defaults.go
- pkg/resourcecreator/deployment.go
- pkg/resourcecreator/deployment_test.go
Fixes #64
Checking against an empty `Probe` object does not work anymore. The real definition of a defined probe is that the `path` is set.
> Use Kubernetes default values for readiness and liveness probes

- README.md
The README had some duplicate fields like `development` aswell as an
empty prerequisites header. I fixed those two issues by combining and
removing the fields respectively.
I also split out the protobuf definition compilation into it's own
subsection.
Made PR so people can comment/ fix the things they don't like.
Does this look good?
> [Documentation] Restructured topics in README

- naiserator.go
- pkg/apis/nais.io/v1alpha1/application_event.go
Fixes the repetition of events, seen in #100
It reduces the spam by associating a counter with events that report the
same message. It works for all kinds of events so everything from
repeating errors to Successful sync messages will be grouped together
and associated with a counter and a timespan in which all the errors
appeared.
What I've done:
I've expanded the reportEvent function to first get all the events for
the current app. Then match based on message and if it finds a matching
message it increments that events counter and updates its lastSeen
timestamp. Then it updates the event.
If it can't find the same event it creates a new one.
Since the feature is implemented in reportEvent it works for all kinds
of events not just Warnings/Errors
I've also made the decision to not to …
> Added counter to application events with same message

- pkg/resourcecreator/leaderelection.go
- pkg/resourcecreator/leaderelection_test.go
- pkg/resourcecreator/resourcecreator.go
Merging #111 correlated with strange errors from users. We're not able to reproduce the error, so we try re-enabling the feature.
> write additional tests for leader election, and re-enable

- cmd/naiserator/config.go
- cmd/naiserator/main.go
- go.mod
- pkg/apis/nais.io/v1alpha1/application_types.go
- pkg/event/generator/generator_test.go
- pkg/kafka/config.go
- pkg/naiserator/config/config.go
- pkg/naiserator/config/config_test.go
- pkg/resourcecreator/const.go
- pkg/resourcecreator/deployment.go
- pkg/resourcecreator/deployment_test.go
- pkg/resourcecreator/proxyopts.go
- pkg/resourcecreator/proxyopts_test.go
- pkg/securelogs/containers.go
- pkg/vault/vaultcontainer.go
- pkg/vault/vaultcontainer_test.go
Today's state of configuration is a largely undocumented mess of command-line flags and environment variables. This patch consolidates all configuration code into a single file. The `viper` library is used to collect the configuration from either command-line flags, environment variables, or a configuration file.
Fixes #94
> Refactor configuration system

- config/nais.io_applications.yaml
- go.mod
- pkg/apis/nais.io/v1alpha1/application_types.go
Neither `spec.accessPolicy.outbound.rules` nor `spec.accessPolicy.outbound.external` is required.
> Outbound.rules is not required

- config/nais.io_applications.yaml
- pkg/apis/nais.io/v1alpha1/application_types.go
- pkg/vault/fixtures/user_secrets.json.golden
- pkg/vault/vaultcontainer.go
- pkg/vault/vaultcontainer_test.go
Lar oss injecte secrets som json, yaml, env eller properties.
Endringen er bakoverkompatibel; hvis "format"-feltet ikke er satt, så er "flatten" default.
Jeg tenker å dark-launche denne featuren, ved å la være å dokumentere at den finnes - så tester vi på noen apper, og hvis det funker som forventet, så forteller vi til utviklerne at den finnes.
> Support multiple formats for vault secret mounting

- pkg/resourcecreator/resourcecreator.go
- pkg/resourcecreator/resourcecreator_test.go
- pkg/resourcecreator/testdata/vanilla_gcp.json
- pkg/resourcecreator/testdata/vanilla_on_premises.json
Updating the service account overwrites the list of secrets, and
triggers creation of new SA tokens
https://github.com/kubernetes/kubernetes/issues/84642
> Do not update service account

- cmd/naiserator/main.go
- pkg/apis/nais.io/v1/jwker_types.go
- pkg/naiserator/config/config.go
- pkg/resourcecreator/const.go
- pkg/resourcecreator/resourcecreator.go
- pkg/resourcecreator/resourceoptions.go
- pkg/resourcecreator/virtualservice.go
- pkg/resourcecreator/virtualservice_test.go
- pkg/vault/vaultcontainer_test.go
PR changes istio gateway resolving mechanism. Today this currently takes the provided ingress, splits the domain and resolves the gateway name based on a naming scheme. 
Instead, this PR makes this resolving explicit as provided configuration where one maps the domain suffix with a fully qualified gateway name.
Example with naiserator.yaml
```
gateway-mappings:
- domainSuffix: .dev-gcp.nais.io
gatewayName: istio-system/ingress-gateway-nais-io
... 
```
Note: Needs update of nais-yaml with mappings before merge
> add explicit mapping of domain suffixes and istio gateways

- pkg/apis/nais.io/v1alpha1/application_types.go
const `JwkerCredentialsFilename` is potentially changed in https://github.com/nais/jwker/pull/2
* the constant seems not to be used in naiserator at all
> chore: remove unused constant (value is changed in jwker)

- pkg/resourcecreator/authorizationpolicy.go
- pkg/resourcecreator/testdata/accesspolicy_gcp.yaml
naiserator erroneously specifies `methods: ['*']`. This field is only supposed to consist of a list of HTTP/gRPC methods. The correct way to specify all methods allowed is to omit the parameter completely.
https://istio.io/latest/docs/reference/config/security/authorization-policy/
This fixes the generation of "KIA0102 Only HTTP methods and fully-qualified gRPC" errors on naiserator-generated AuthorizationPolicies.
> Omit invalid method

- config/crd/nais.io_applications.yaml
- pkg/apis/nais.io/v1/azureadapplication_types.go
- pkg/apis/nais.io/v1alpha1/application_types.go
- pkg/resourcecreator/azureadapplication.go
- pkg/resourcecreator/testdata/azureadapplication_full.yaml
- pkg/resourcecreator/testdata/azureadapplication_minimal.yaml
- pkg/resourcecreator/testdata/azureadapplication_tenant.yaml
Allow user-configurable Azure AD tenant target. Empty field results in no annotation which is treated as before - the logic for this exists in azurerator
> user-configurable Azure AD tenant target

- pkg/resourcecreator/deployment.go
- pkg/resourcecreator/testdata/tracing.yaml
tracing == 0 because tracing is still propagated if the span ID headers are generated by the library in question.
Generation of these headers might be a useful feature in the future.
> Create istio proxy annotation

- pkg/resourcecreator/authorizationpolicy.go
- pkg/resourcecreator/authorizationpolicy_test.go
If an application _only_ defines an inbound access policy rule for a non-local application (i.e. the application belongs to a different cluster), we should not create an istio authorization policy as the rule contains an empty `from.source`.
That is, this:
```yaml
accessPolicy:
inbound:
rules:
- application: hjelpemidlerdigitalsoknad-api
namespace: teamdigihot
cluster: dev-fss
```
results in this:
```
admission webhook "validation.istio.io" denied the request: configuration is invalid: `from.source` must not be empty, found at rule 2 in digihot-altinn-proxy.teamdigihot" 
```
This PR fixes this by only appending a rule to the authorization policy if the list of inbound principals is non-empty.
> fix: ensure that istio access policy rules have non-empty sources

- pkg/resourcecreator/resourcecreator.go
- pkg/resourcecreator/testdata/vanilla_gcp.yaml
Some applications need a workload identity outside of buckets/sqlinstances that can be assigned permissions out-of-band to another project that owns some centrally managed resources.
> create google serviceaccounts for all gcp deployments by default

- pkg/resourcecreator/ingress.go
- pkg/resourcecreator/testdata/ingress_linkerd.yaml
If multiple ingresses on the same gateway are specified, they will now
overwrite each other in the `ingresses` map because `host` is used as
map key, while the `ingressClass` is used in the ingress resource name.
This fix uses the `ingressClass` as key for the `ingresses` map.
> Support multiple hosts on the same ingress gw

- pkg/resourcecreator/google/sql/user.go
- pkg/resourcecreator/testdata/gcp_database_additional_users.yaml
- pkg/resourcecreator/testdata/gcp_database_custom_env_additional_users.yaml
- pkg/resourcecreator/testdata/naisjob/cronjob_gcp_database_additional_users.yaml
- pkg/resourcecreator/testdata/naisjob/cronjob_gcp_database_custom_env_additional_users.yaml
As per https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqluser,
the default behaviour for SQLUser is to use `metadata.name` as the name
of the SQL user. We've set this to be `$sqlinstance-$clean(user)-$hash` for
any additional users. However, this results in a mismatch between the
actual SQL username that is provisioned and the desired username
(the latter of which is also used in the generated secret) - and
ultimately causes authentication errors.
This commit fixes this by specifying the `resourceID` field and setting
the value of this to the desired username for additional users only.
> fix(google/sql): ensure that resource ID is set for additional users

- pkg/resourcecreator/poddisruptionbudget/poddisruptionbudget.go
- pkg/resourcecreator/testdata/vanilla_gcp.yaml
- pkg/resourcecreator/testdata/vanilla_on_premises.yaml
Previously, we set `minAvailable` in the PDB to be equal to the minimum desired
replica count - which in most cases results in the PDB not allowing any
disruptions because `count(pods) == minAvailable`. This effectively
halts draining of nodes containing pods affected by these PDBs, and in
the case of GKE will force-delete these pods when the grace period of 1
hour passes.
By setting the `maxUnavailable` to 1 we allow for a maximum of 1 disrupted
pod during upgrades. This comes with the caveat of effectively disabling PDBs
for applications that have set the minimum replica count to 1 and have not been
scaled up by the HPA at the time of the drain. However, one could argue that
users desiring high availability of their applications should specify at least
2 minimum replicas.
> fix(poddisruptionbudget): use maxUnavailable instead of minAvailable

- pkg/resourcecreator/batch/job.go
- pkg/resourcecreator/deployment/deployment.go
- pkg/resourcecreator/pod/pod.go
- pkg/resourcecreator/testdata/opt_in_securitycontext.yaml
- pkg/resourcecreator/testdata/vanilla_on_premises.yaml
Note: also fixes bug where if max == min, we set the replicas in the deployment to what is specified in resourceoptions. This didn't matter before as we always created HPA
Co-authored-by: Roger Bjørnstad <roger.bjornstad@nav.no>
Co-authored-by: Sten Ivar Røkke <sten.ivar.rokke@nav.no>
> restricted securitycontext as optin

- pkg/metrics/metrics.go
- pkg/synchronizer/synchronizer.go
Modify synchronizer to add meta fields for cluster operation functions.
https://trello.com/c/XFcFczuY/74-legge-p%C3%A5-kind-label-p%C3%A5-resourceswritten-metrikken
> Add `kind` label to `metrics.ResourcesGenerated`.

- pkg/resourcecreator/poddisruptionbudget/poddisruptionbudget.go
- pkg/resourcecreator/poddisruptionbudget/poddisruptionbudget_test.go
Currently, if a PDB is created with min replicas set to 1 and max > 1,
the PDB will disallow any disrupted pods if the deployment only has a
single active replica at the time of draining. This results in the
draining process of the node to halt, which is undesirable. Applications
requiring zero disruptions should specify minimum 2 replicas.
> fix(poddisruptionbudget): skip creating PDB if min replicas is set to 1

- .gitignore
- Dockerfile
- Makefile
- cmd/naiserator_webhook/main.go
After discussions on slack, we might want to separate the webhook server into a separate service. This creates a new binary in the dockerfile which allows to use similar workflow as the existing one, but running a separate deployment for webhook.
This requires some additional changes:
- Create new Deployment and Service
- Update Certificates to match the new service name
- Update ValidatingWebhookConfiguration with new CA Bundle and service
After the change, we can remove the feature gate code from the main executable.
> Create separate webhook executable.

- pkg/resourcecreator/google/gcp/gcp.go
- pkg/resourcecreator/google/storagebucket/storagebucket.go
- pkg/resourcecreator/testdata/gcp_buckets_uniformlevelaccess.yaml
Set up IAMPolicyMember for buckets with uniform-bucket-level-access, in addition to the existing role `roles/storage.objectViewer`:
* `roles/storage.legacyObjectOwner`
* `roles/storage.legacyBucketOwner`
The IAMPolicyMember resources are also given distinct names to avoid naming collisions and length limitations.
> gcp/buckets: uniform bucket level access

- pkg/resourcecreator/pod/pod.go
- pkg/resourcecreator/testdata/naisjob/cronjob_features_on_premises.yaml
- pkg/resourcecreator/testdata/naisjob/job_features_on_premises.yaml
- pkg/resourcecreator/testdata/naisjob/vanilla_cronjob_on_premises.yaml
- pkg/resourcecreator/testdata/naisjob/vanilla_job_on_premises.yaml
i just want to run this through here instead of pushing it straight to master. @ me on slack if you'd like to talk face to face about this stuff.
the short story about what's been done with hahaha the past few days:
* hahaha was deployed to every cluster on thursday or friday (can't remember exactly).
* team bømlo (namespace `tbd` in dev/prod-fss clusters) had issues on friday/monday where their namespace had gotten flooded by naisjobs that never reached completion. ginuudan simply hadn't done its job. no surprise there, tbh. i think it happens rather often.
* [a feature flag was added](https://github.com/nais/naiserator/pull/318/files#diff-16cc038e2ade22e27e055c59c9ffdf517fc834d72d4446bd7f5d38e2d74bec36L360-L361) in naiserator and bømlo could switch over to using hahaha as their janitor. …
> disable ginuudan for new naisjob deployments, enable hahaha

- updater/updater.go
Dette betyr at FindAll-metoden aldri har fungert som ønskelig.
> fix: må ta vare på returverdien

- pkg/synchronizer/synchronizer.go
- pkg/synchronizer/synchronizer_test.go
Etter oppgradering til k8s v1.20 så kan ikke lengre ha ownerReference på tvers av namespaces. Derfor må vi ha et annet system for å kunne rydde opp i CNRM-namespacet vårt.
Her så legger vi på en finalizer som lar oss plukke opp når en nais-app blir slettet, og så slette alle tilhørende iampolicy og iamserviceaccounts i namespace serviceaccount.
> feat: finalizer for opprydding i serviceaccount-namespace

- pkg/resourcecreator/batch/job.go
- pkg/resourcecreator/testdata/naisjob/job_features_on_premises.yaml
- pkg/resourcecreator/testdata/naisjob/vanilla_job_on_premises.yaml
- pkg/synchronizer/synchronizer.go
- updater/updater.go
For at sletting av en job skal fungere som ønsket trenger vi å være
sikker på at job-en er ryddet bort før vi lager den på nytt. Dette er
for å unngå race-condition. Vi må også bruke propagation policy for å
påse at pod-er tilknyttet en job også blir slettet.
> feat: sletter job ved endring

- README.md
The README currently includes a dead link to the nais docs page. Expected behaviour would be for it to lead to the nais Application reference page. This PR fixes that dead link.
> Update dead link

- pkg/resourcecreator/networkpolicy/networkpolicy.go
- pkg/resourcecreator/testdata/accesspolicy_only_other_clusters.yaml
Previously, an app could define an access policy as follows:
```yaml
spec:
...
accessPolicy:
inbound:
rules:
- application: bar
namespace: baz
cluster: othercluster
outbound:
rules:
- application: foo
namespace: bar
cluster: othercluster
```
As network policies aren't applicable for other clusters, the resulting `[]networkingv1.NetworkPolicyPeer` returned from https://github.com/nais/naiserator/blob/f9c7fbb863048e9d0a3b00bd9345cace7e6132c5/pkg/resourcecreator/networkpolicy/networkpolicy.go#L95-L119 would be empty for the above example. The peers were added to both an ingress and egress rule, which results in a `NetworkPolicy` that contains empty rules:
```yaml
spec:
ingress:
...
- {}
egress:
...
- {}
```
...which effectively allows all traffic as noted by the `from` and `to` fields for …
> fix(networkpolicy): do not add ingress/egress rules for empty list of peers

- updater/updater.go
- updater/updater_test.go
Fixes: https://trello.com/c/lYWpxdVl/219-forhindre-at-to-applikasjoner-definerer-samme-sqlinstance
> Don't touch resources with differing ownerReference metadata

- charts/values.yaml
- pkg/resourcecreator/google/helpers.go
- pkg/resourcecreator/leaderelection/leaderelection.go
- pkg/resourcecreator/pod/pod.go
- pkg/resourcecreator/testdata/additional_kernel_capabilities.yaml
- pkg/resourcecreator/testdata/azureadapplication_wonderwall_minimal.yaml
- pkg/resourcecreator/testdata/idporten_wonderwall_minimal.yaml
- pkg/resourcecreator/testdata/naisjob/cronjob_features_on_premises.yaml
- pkg/resourcecreator/testdata/naisjob/job_features_on_premises.yaml
- pkg/resourcecreator/testdata/naisjob/vanilla_cronjob_on_premises.yaml
- pkg/resourcecreator/testdata/naisjob/vanilla_job_on_premises.yaml
- pkg/resourcecreator/testdata/vanilla_gcp.yaml
- pkg/resourcecreator/testdata/vanilla_on_premises.yaml
- pkg/resourcecreator/wonderwall/wonderwall.go
updated capabilities to use the right value for drop "ALL". update tests accordingly.
Co-authored-by: Frode Sundby <frode.sundby@nav.no>
Co-authored-by: Thomas Siegfried Krampl <thomas.siegfried.krampl@nav.no>
> add: secomp profile with Runtime default for pod and container

- charts/templates/netpol.yaml
After
https://github.com/nais/aivenator/commit/89904b94fb36add63966e2e2710189a1efea5e82, naiserator is unable to access the apiserver because it has the `kafka=enabled` label.
This commit adds a netpol using the existing value for allowing apiserver access.
> chart: Add networkpolicy for apiserver access

- go.mod
- go.sum
- pkg/resourcecreator/networkpolicy/networkpolicy.go
- pkg/resourcecreator/testdata/accesspolicy_legacy_gcp.yaml
- pkg/resourcecreator/testdata/vanilla_legacy_gcp.yaml
* add prometheus network policy rule for legacy instead of overwriting
* add ingress network policy for both new and old loadbalancers
Co-authored-by: Thomas Krampl <thomas.siegfried.krampl@nav.no>
Co-authored-by: rbjornstad <roger.bjornstad@nav.no>
Co-authored-by: Terje Sannum <terje.sannum@nav.no>
> add network policies for legacy cluster

- pkg/resourcecreator/networkpolicy/networkpolicy.go
- pkg/resourcecreator/testdata/accesspolicy_ingress_allow_all.yaml
Some teams have applications that they want to allow inbound traffic to from various pods within the cluster - without having to manually manage an ever-growing list of applications.
This PR adds wildcard support to namespaces so that our users don't have to create and maintain their own NetworkPolicy for this use case.
> networkpolicy: support wildcard namespaces for inbound traffic

- pkg/resourcecreator/pod/pod.go
- pkg/resourcecreator/pod/pod_test.go
Currently the following application spec does not work:
```yaml
filesFrom:
- emptyDir:
medium: Memory
mountPath: /app/.next/cache
```
It results in the following error:
```
Error: Status: failure: Application/swag-shop (FailedSynchronization): persisting Deployment to Kubernetes: Invalid: Deployment.apps "swag-shop" is invalid: [spec.template.spec.volumes[2].name: Invalid value: "app-.next-cache": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?'), spec.template.spec.containers[0].volumeMounts[6].name: Not found: "app-.next-cache"] (total of 1 errors)
```
This pull requests replaces everything that is not …
> Make generateNameFromMountPath work for paths with special chars in them

- charts/naiserator/values.yaml
Hovedsakelig oppgradert avhengigheter, og Go til v1.20. Ellers er det disse endringene:
- require login_token with token and enable_iam_login (#1641) (48a2fe5)
- deprecate proxy drivers (#1500) (2b460ea)
- Downscope OAuth2 token included in ephemeral certificate (#1450) (7557a35)
- add support for ReadTime in Admin API requests (#1040) (a7c8b5c)
- add support for specifying a quota project (#1044) (dc66aca)
- allow multiple -instances flags (#1046) (1972693), closes #1030
- add health checks to proxy (#859) (ea62bdd)
- add instance dialing to health check (#871) (eca3793)
- require TLS v1.3 at minimum (#906) (cafa966)
> feat: bump CloudSqlProxy til v1.33.9

- charts/naiserator/templates/netpol.yaml
- pkg/resourcecreator/networkpolicy/networkpolicy.go
- pkg/resourcecreator/observability/observability.go
- pkg/resourcecreator/testdata/accesspolicy_ingress.yaml
- pkg/resourcecreator/testdata/accesspolicy_ingress_allow_all.yaml
- pkg/resourcecreator/testdata/accesspolicy_legacy_gcp.yaml
- pkg/resourcecreator/testdata/accesspolicy_max.yaml
- pkg/resourcecreator/testdata/accesspolicy_only_other_clusters.yaml
- pkg/resourcecreator/testdata/accesspolicy_tokenx.yaml
- pkg/resourcecreator/testdata/leader_election.yaml
- pkg/resourcecreator/testdata/naisjob/cronjob_accesspolicy_egress.yaml
- pkg/resourcecreator/testdata/observability_tracing_enabled.yaml
- pkg/resourcecreator/testdata/vanilla.yaml
- pkg/resourcecreator/testdata/vanilla_legacy_gcp.yaml
Use the `kubernetes.io/metadata.name` label, which the API server sets for all namespaces with uniqueness and immutability guarantees. Its value is set to the name of the namespace.
https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetes-io-metadata-name
> netpol: use `kubernetes.io/metadata.name` as namespace selector label

- pkg/resourcecreator/google/gcp/gcp.go
- pkg/resourcecreator/testdata/gcp_bigquery.yaml
- pkg/resourcecreator/testdata/gcp_bigquery_cascading_delete.yaml
- pkg/resourcecreator/testdata/gcp_buckets.yaml
- pkg/resourcecreator/testdata/gcp_buckets_publicaccessprevention.yaml
- pkg/resourcecreator/testdata/gcp_buckets_uniformlevelaccess.yaml
- pkg/resourcecreator/testdata/gcp_buckets_with_lifecycle_and_retention.yaml
- pkg/resourcecreator/testdata/gcp_database.yaml
- pkg/resourcecreator/testdata/gcp_database_with_insights.yaml
- pkg/resourcecreator/testdata/naisjob/cronjob_gcp_bigquery_cascading_delete.yaml
- pkg/resourcecreator/testdata/naisjob/cronjob_gcp_buckets.yaml
- pkg/resourcecreator/testdata/naisjob/cronjob_gcp_database.yaml
The `GOOGLE_CLOUD_PROJECT` environment variable is default in Google SDKs which
means less manual configurations for teams authetnticating to Google Cloud.
* java https://github.com/googleapis/google-cloud-java/blob/cc0e248a9ee4658dbd3b2649d01381df218b4419/README.md?plain=1#L214
* node https://github.com/googleapis/google-cloud-node/blob/489e188d97af302f96299a5b40eb5e07020972fc/docs/authentication.md?plain=1#L25
> Add support for GOOGLE_CLOUD_PROJECT environment variable

- pkg/resourcecreator/google/helpers.go
- pkg/resourcecreator/pod/helpers.go
- pkg/resourcecreator/testdata/gcp_database.yaml
Benchmarks with pgbench has shown that applications with high traffic are severely limited by the CPU resourc limits. This commits removes the limit, but keeps the request.
Also, CPU request is bumped by 150%, up to 50 millicpu.
> Remove Cloud SQL proxy CPU limit

- charts/naiserator/Chart.yaml
- charts/naiserator/values.yaml
- pkg/resourcecreator/google/helpers.go
- pkg/resourcecreator/testdata/gcp_database.yaml
- pkg/resourcecreator/testdata/gcp_database_with_insights.yaml
- pkg/resourcecreator/testdata/naisjob/cronjob_gcp_database.yaml
- pkg/synchronizer/synchronizer_test.go
Previous version 1.33.9; followed release notes/upgrade guide at:
https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/0184be312bba666a6a74d799bfc3c216dfdd812f/migration-guide.md
> Upgrade Google Cloud SQL proxy to version 2.8

- charts/naiserator/Feature.yaml
- charts/naiserator/values.yaml
- pkg/naiserator/config/config.go
- pkg/resourcecreator/observability/observability.go
- pkg/resourcecreator/observability/observability_test.go
- pkg/resourcecreator/testdata/observability_tracing_enabled.yaml
- pkg/resourcecreator/testdata/observability_tracing_enabled_error.yaml
* Changed endpoint from tempo to opentelemetry collector
* Make it configurable if we want to change things later
* Refactored trace specifics to more generic otel names
* Better test coverage for observability utility functions
* Fail sync if otel is not configured for the cluster
> Use OpenTelemetry Collector endpoint for Trace config

- pkg/resourcecreator/pod/pod.go
- pkg/resourcecreator/resource/source.go
- pkg/resourcecreator/testdata/env.yaml
- pkg/resourcecreator/testdata/gcp_gar_toleration_with_non_gar_image.yaml
- pkg/resourcecreator/testdata/naisjob/cronjob_features_on_premises.yaml
- pkg/resourcecreator/testdata/naisjob/job_features_on_premises.yaml
- pkg/resourcecreator/testdata/naisjob/vanilla_cronjob_on_premises.yaml
- pkg/resourcecreator/testdata/naisjob/vanilla_job_on_premises.yaml
- pkg/resourcecreator/testdata/vanilla.yaml
- pkg/resourcecreator/testdata/vanilla_on_premises.yaml
PORT defaults to 8080 if not specified, uses `.spec.port` if provided. BIND_ADDRESS defaults to `0.0.0.0:<PORT>`.
If user provides envs directly, these will take precedence
> Adds default env vars for PORT and BIND_ADDRESS

- pkg/resourcecreator/poddisruptionbudget/poddisruptionbudget.go
- pkg/resourcecreator/testdata/vanilla.yaml
- pkg/resourcecreator/testdata/vanilla_legacy_gcp.yaml
- pkg/resourcecreator/testdata/vanilla_on_premises.yaml
The default behaviour for PDBs only allows eviction of running pods (`status.phase="Running"`) if the application is not disrupted (`.status.currentHealthy` is at least equal to `.status.desiredHealthy`). This means that misbehaving pods (e.g. in CrashLoopBackOff) count towards the budget. In some cases this may indefinitely halt operations such as node drains.
By configuring `unhealthyPodEvictionPolicy` to `AlwaysAllow`, running pods that are not yet healthy may be unconditionally evicted.
This feature has been available in beta since Kubernetes 1.27 and will graduate in 1.31.
See also https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/3017-pod-healthy-policy-for-pdb/README.md.
> feat(poddisruptionbudget): always allow eviction of unhealthy pods

- pkg/resourcecreator/google/sql/instance.go
- pkg/resourcecreator/testdata/gcp_database_shared_vpc.yaml
- pkg/resourcecreator/testdata/naisjob/cronjob_gcp_database_shared_vpc.yaml
In some situations, a sqlinstance might have existing certs for an application that we don't know about in the cluster. If we try to make new certs with the same common name, it will fail, and the only solution is to use the gcp console to remove the previous cert.
By adding a random suffix, we avoid those collisions, at the cost of some additional certs on the instance that we in probably have lost anyway.
> Add random suffix to common name for sqlsslcerts to avoid collision

- pkg/resourcecreator/networkpolicy/networkpolicy.go
- pkg/resourcecreator/testdata/accesspolicy_legacy_gcp.yaml
- pkg/resourcecreator/testdata/accesspolicy_max.yaml
Opprinnelig så slo vi sammen alle utgående hosts/ports, som gjorde at man kunne ende opp med en ipBlock-regel ble slått sammen med en namespace-regel.
nais.yaml:
```yaml
accessPolicy:
outbound:
external:
- host: test.maskinporten.no
- host: io.fiks.test.ks.no
ports:
- port: 5671
- ipv4: 34.88.234.148
ports:
- port: 5432
- port: 3307
rules:
- application: barn-bvr-api
namespace: barnevern
```
Output (netpol):
```yaml
egress:
- to:
- namespaceSelector: {}
podSelector:
matchLabels:
k8s-app: kube-dns
- to:
- ipBlock:
cidr: 10.12.0.0/24
- ports:
- port: 5432
protocol: TCP
- port: 3307
protocol: TCP
to:
- namespaceSelector:
matchLabels:
kubernetes.io/metadata.name: barnevern
podSelector:
matchLabels:
app: barn-bvr-api
- ipBlock:
cidr: 34.88.234.148/32
```
Her ser vi hvordan ting klumper seg …
> fix: en regel per utgående

- pkg/resourcecreator/google/gcp/gcp.go
- pkg/resourcecreator/pod/pod.go
The new team logs needs to know the Google Cloud Project ID for the team in order to send the logs to the right Cloud Logging instance.
Co-authored-by: Terje Sannum <terje.sannum@nav.no>
> Ensure GOOGLE_CLOUD_PROJECT is set whenever applicable

- pkg/synchronizer/synchronizer.go
- pkg/synchronizer/synchronizer_test.go
This cleans up the Postgresql and NetworkPolicies created for the app in the postgres namespace.
The IAMPolicy that gets created is shared between all applications in the same namespace, so that can not be deleted.
I attempted to extend TestSynchronizer to test this, but adding the AcidZalandoListers makes the test fail because the responses from the envtest fake api-server seem to trigger incorrect lookups when controller-runtime attempts to identify the correct GVK->Type mapping. This is caused by Zalando using `postgresql` instead of `Postgresql` and controller-runtime making assumptions all over the place. For some reason it works when running with a real cluster, presumably other assumptions works better :shrug:
> Delete postgres resources when an application is deleted
