nais/naiserator

doc/migrating.md

The existing link does not work. Looks like the file name has been changed.

Update path to example .yaml

---

naiserator.go
pkg/resourcecreator/deployment.go
pkg/resourcecreator/deployment_test.go
pkg/resourcecreator/resourcecreator.go
pkg/resourcecreator/resourcecreator_test.go
pkg/resourcecreator/resourceoptions.go

Match existing number of replicas in deployment

---

pkg/apis/naiserator/v1alpha1/application.yaml
pkg/apis/naiserator/v1alpha1/types.go
pkg/resourcecreator/deployment.go
pkg/resourcecreator/deployment_test.go

Revert "Add support for env var sources"

---

pkg/apis/naiserator/v1alpha1/application.yaml
pkg/apis/naiserator/v1alpha1/types.go
pkg/resourcecreator/deployment.go
pkg/resourcecreator/deployment_test.go

Resolves issue in https://github.com/nais/naiserator/pull/60 and reintroduce change

Fix support for env var sources

---

pkg/resourcecreator/deployment.go

Gjort leaderelection immutable

---

naiserator.go
pkg/apis/naiserator/v1alpha1/defaults.go
pkg/resourcecreator/deployment.go
pkg/resourcecreator/deployment_test.go
pkg/resourcecreator/horizontalpodautoscaler_test.go
pkg/resourcecreator/ingress_test.go
pkg/resourcecreator/istio_test.go
pkg/resourcecreator/networkpolicy.go
pkg/resourcecreator/networkpolicy_test.go
pkg/resourcecreator/resourcecreator.go
pkg/resourcecreator/resourcecreator_test.go
pkg/resourcecreator/service_test.go
pkg/resourcecreator/serviceaccount_test.go
pkg/resourcecreator/virtualservice.go
pkg/resourcecreator/virtualservice_test.go
pkg/test/fixtures/fixtures.go
pkg/vault/vaultcontainer_test.go

Implement missing tests and refactor existing ones in an attempt to make test writing more approachable.

Test refactoring

---

examples/nais-max.yaml
pkg/resourcecreator/istio.go

Fixes on Istio RBAC resources for zero trust.

Defined user for ServiceRoleBinding and allow all services in ns

---

pkg/resourcecreator/istio.go
pkg/resourcecreator/istio_test.go

Apps with Prometheus enabled needs access to istio-system default SA

---

go.mod
pkg/resourcecreator/deployment.go
pkg/resourcecreator/deployment_test.go
pkg/vault/vaultcontainer.go
pkg/vault/vaultcontainer_test.go

Only create one vault sidecar

---

pkg/util/strings_test.go

Until somebody fixes whatever Kyrre broke

Add breaking test

---

pkg/resourcecreator/resourcecreator.go

Merging this change will result in many `role` and `rolebinding` resources being removed from existing applications that might still use them due to having them from earlier _naisd_ deployments.

Remove leader election pod for applications without leaderElection: true

---

go.mod
pkg/vault/fixtures/default.json.golden
pkg/vault/vaultcontainer_test.go

When trying to  rewrite the vault code to use a different image, I found it difficult to write test
thus leading me to try another approach: golden files. 
See https://medium.com/@jarifibrahim/golden-files-why-you-should-use-them-47087ec994bf
for details. 
Would like your opinions if this is something that you would accept.

Use golden file for testing Vault integration

---

pkg/resourcecreator/resourcecreator.go

Deletes the following istio resources if they are not longer needed:
- VirtualService
- ServiceRoleBinding for app
- ServiceRoleBinding for Prometheus
- ServiceEntry

Deleting istio resources if not longer needed

---

pkg/resourcecreator/leaderelection.go
pkg/resourcecreator/testdata/vanilla_gcp.json
pkg/resourcecreator/testdata/vanilla_on_premises.json

Trenger kun get og update for leader election

---

pkg/resourcecreator/deployment.go
pkg/resourcecreator/testdata/liveness_readiness.json

auto-prefix probe paths with leading slash if missing from app spec

---

pkg/synchronizer/synchronizer.go
pkg/synchronizer/synchronizer_test.go

Enable deletion of orphan objects

---

go.mod
pkg/apis/nais.io/v1alpha1/application_types.go
pkg/resourcecreator/newgoldenfile_test.go
pkg/resourcecreator/resourcecreator_golden_files_test.go
pkg/resourcecreator/testdata/vanilla_gcp.yaml
pkg/resourcecreator/testdata/vault.json
pkg/test/deepcomp/deepcomp.go
pkg/test/deepcomp/deepcomp_test.go
pkg/test/deepcomp/diffset.go

New test runner based on YAML fixtures. Makes it possible to test regular expressions, and simplifies test fixture syntax.

Golden files test runner v2

---

config/nais.io_applications.yaml
pkg/apis/nais.io/v1alpha1/application_types.go
pkg/apis/nais.io/v1alpha1/zz_generated.deepcopy.go
pkg/resourcecreator/deployment.go
pkg/resourcecreator/testdata/liveness_readiness.yaml
pkg/resourcecreator/testdata/startup_probe.yaml

Support startup probes

---

Makefile

fix: correct output directory for crd

---

pkg/resourcecreator/virtualservice.go
pkg/resourcecreator/virtualservice_test.go

while transitioning to new istio gateways

support comma separated gw mappings

---

pkg/resourcecreator/deployment.go
pkg/resourcecreator/testdata/kafkarator.yaml

Waiting for https://github.com/nais/kafkarator/pull/7

Add env-variables for kafkarator provided schema registry credentials

---

config/crd/nais.io_applications.yaml
pkg/apis/nais.io/v1alpha1/application_types.go
pkg/apis/nais.io/v1alpha1/defaults.go
pkg/apis/nais.io/v1alpha1/zz_generated.deepcopy.go
pkg/resourcecreator/authorizationpolicy.go
pkg/resourcecreator/authorizationpolicy_test.go
pkg/resourcecreator/azureadapplication.go
pkg/resourcecreator/idportenclient.go
pkg/resourcecreator/ingress.go
pkg/resourcecreator/ingress_test.go
pkg/resourcecreator/networkpolicy_test.go
pkg/resourcecreator/resourcecreator_test.go
pkg/resourcecreator/virtualservice.go
pkg/resourcecreator/virtualservice_test.go
pkg/synchronizer/synchronizer_test.go

Fail fast when ingresses aren't formatted correctly.

Regex match "https://" ingress fields

---

Makefile
pkg/resourcecreator/deployment.go
pkg/resourcecreator/resourcecreator_golden_files_test.go
pkg/resourcecreator/testdata/prometheus_not_enabled.yaml
pkg/resourcecreator/testdata/vanilla_on_premises.yaml
pkg/test/deepcomp/deepcomp.go
pkg/test/deepcomp/diffset.go

Omit Prometheus annotations unless explicitly enabled in Application spec

Disable prometheus

---

config/crd/nais.io_applications.yaml
pkg/apis/nais.io/v1alpha1/application_types.go
pkg/resourcecreator/googlesqlinstance.go

Co-authored-by: @gorzan  <goran.berntsen@nav.no>
Ref: https://nav-it.slack.com/archives/C0190SV7KSN/p1607085792014000?thread_ts=1607025343.474100&cid=C0190SV7KSN

feature(gcp-postgresql): Allow users to set Collation for DB

---

Makefile
pkg/resourcecreator/deployment.go
pkg/resourcecreator/testdata/vanilla_on_premises.yaml

Implemented in https://github.com/navikt/nais-yaml/pull/114

Feature(docker_pull): Add reference to GitHub Container Registry token

---

pkg/controllers/naisjob.go
pkg/resourcecreator/batch/job.go
pkg/resourcecreator/testdata/naisjob/cronjob_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/job_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_cronjob_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_job_on_premises.yaml
pkg/synchronizer/naisjob_synchronizer.go

* Should not manuallty add spec.selector, for Jobs, this is auto generated-uid
* Fixed issue with NaisJobReconiler and source object in parameters:

fix: Jobs should use auto-gen spec.selector

---

go.mod
go.sum
hack/resources/02-clusterrole.yaml
pkg/resourcecreator/kafka/kafka.go
pkg/resourcecreator/resourcecreator.go
pkg/resourcecreator/testdata/kafkarator.yaml

This switches from using the secrets created by Kafkarator to request a secret from Aivenator via the AivenApplication resource.

Use Aivenator for Kafka-secrets

---

go.mod
go.sum
pkg/resourcecreator/accesspolicy/helpers.go
pkg/resourcecreator/azure/azureadapplication.go
pkg/resourcecreator/jwker/jwker_test.go
pkg/resourcecreator/networkpolicy/networkpolicy.go
pkg/resourcecreator/networkpolicy/networkpolicy_test.go
pkg/resourcecreator/testdata/azureadapplication_full.yaml

Doc: https://github.com/nais/doc/pull/205
Merge after https://github.com/nais/liberator/pull/15 and https://github.com/nais/azurerator/pull/3

accesspolicy, azureadapplication: use updated inbound rules spec

---

cmd/naiserator/main.go
pkg/naiserator/config/config.go
pkg/synchronizer/naisjob_synchronizer.go
pkg/synchronizer/synchronizer.go

Co-Authored-By: @x10an14 <christian.chavez@nav.no>
Co-Authored-By: @ambientsound <kim.tore.jensen@nav.no>

Create a GCP feature flag in config.

---

go.mod
go.sum
pkg/resourcecreator/deployment/deployment.go
pkg/resourcecreator/testdata/cleanup.yaml
pkg/resourcecreator/testdata/cleanup_not_all_fields.yaml
pkg/resourcecreator/testdata/cleanup_override_defaults.yaml

- To be in sync with https://github.com/nais/liberator/pull/23

Change rollback => strategy

---

cmd/naiserator/main.go
go.mod
go.sum

Register webhooks defined in liberator on the manager.

Immutability webhook

---

pkg/resourcecreator/pod/pod.go
pkg/resourcecreator/testdata/naisjob/cronjob_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/job_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_cronjob_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_job_on_premises.yaml

This adds an annotation for Ginuudan to do its thing for every Naisjob.

add ginuudan annotation for cleanup

---

cmd/naiserator/main.go
pkg/naiserator/config/config.go
pkg/resourcecreator/pod/pod.go
pkg/resourcecreator/resource/options.go
pkg/resourcecreator/testdata/additional_kernel_capabilities.yaml
pkg/resourcecreator/testdata/naisjob/cronjob_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/job_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_cronjob_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_job_on_premises.yaml
pkg/resourcecreator/testdata/vanilla_gcp.yaml
pkg/resourcecreator/testdata/vanilla_on_premises.yaml

Security context opt-out

---

go.mod
go.sum
pkg/resourcecreator/google/storagebucket/storagebucket.go
pkg/resourcecreator/testdata/gcp_buckets_uniformlevelaccess.yaml

Co-authored-by: Sten Røkke <sten.ivar.rokke@nav.no>
venter på https://github.com/nais/liberator/pull/35

feat: støtte for uniformbucketlevelaccess

---

go.mod
go.sum
pkg/synchronizer/monitoring.go
pkg/synchronizer/synchronizer.go
pkg/synchronizer/synchronizer_test.go

Deployd skiller ikke mellom naisjob med og uten schedule, så vi
trenger å rapportere tilbake at vi er ferdig med alle typer naisjobs

feat: trenger å monitor alle naisjob

---

go.mod
go.sum
pkg/resourcecreator/azure/azureadapplication.go
pkg/resourcecreator/testdata/azureadapplication_wonderwall_full.yaml
pkg/resourcecreator/testdata/idporten_wonderwall_full.yaml
pkg/resourcecreator/wonderwall/wonderwall.go

Depends on https://github.com/nais/liberator/pull/56.

wonderwall: ignore health probe and metrics paths for auto-login

---

pkg/generators/application.go
pkg/generators/config.go
pkg/generators/naisjob.go
pkg/naiserator/config/config.go
pkg/resourcecreator/certificateauthority/certificateauthority.go
pkg/resourcecreator/jwker/jwker_test.go
pkg/resourcecreator/testdata/naisjob/cronjob_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/job_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_cronjob_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_job_on_premises.yaml
pkg/resourcecreator/testdata/vanilla_on_premises.yaml

Feature flag for enabling NAV CA bundle

---

pkg/resourcecreator/networkpolicy/networkpolicy.go
pkg/resourcecreator/networkpolicy/networkpolicy_test.go
pkg/resourcecreator/testdata/accesspolicy_linkerd.yaml
pkg/resourcecreator/testdata/accesspolicy_nais_system.yaml
pkg/resourcecreator/testdata/accesspolicy_only_other_clusters.yaml
pkg/resourcecreator/testdata/vanilla_gcp.yaml

Co-authored-by: thokra-nav <thomas.siegfried.krampl@nav.no>

Add labels for prometheus in naas-clusters

---

pkg/resourcecreator/networkpolicy/networkpolicy.go
pkg/resourcecreator/networkpolicy/networkpolicy_test.go
pkg/resourcecreator/testdata/accesspolicy_linkerd.yaml
pkg/resourcecreator/testdata/accesspolicy_nais_system.yaml
pkg/resourcecreator/testdata/accesspolicy_only_other_clusters.yaml
pkg/resourcecreator/testdata/vanilla_gcp.yaml

remove linkerd viz netpols

---

cmd/naiserator/main.go
pkg/resourcecreator/ingress/ingress.go
pkg/resourcecreator/testdata/azureadapplication_wonderwall_full.yaml
pkg/resourcecreator/testdata/azureadapplication_wonderwall_minimal.yaml
pkg/resourcecreator/testdata/azureadapplication_wonderwall_refresh.yaml
pkg/resourcecreator/testdata/idporten_wonderwall_full.yaml
pkg/resourcecreator/testdata/idporten_wonderwall_minimal.yaml
pkg/resourcecreator/testdata/ingress_on_premises.yaml
pkg/synchronizer/synchronizer_test.go

Apply nginx ingress annotations for all environments.
ToDo:

Create nginx ingress for all

---

charts/values.yaml
pkg/generators/config.go
pkg/naiserator/config/config.go
pkg/resourcecreator/pod/pod.go
pkg/resourcecreator/testdata/additional_kernel_capabilities.yaml
pkg/resourcecreator/testdata/additional_kernel_capabilities_seccomp.yaml
pkg/resourcecreator/testdata/naisjob/cronjob_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/job_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_cronjob_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_job_on_premises.yaml
pkg/resourcecreator/testdata/vanilla_gcp.yaml
pkg/resourcecreator/testdata/vanilla_on_premises.yaml

Remove feature flag and logic for handling rollout of secure pod context as default

---

pkg/resourcecreator/google/sql/instance.go
pkg/resourcecreator/google/sql/instance_flags.go
pkg/resourcecreator/google/sql/instance_flags_test.go

Fixes https://github.com/nais/features/issues/34

Validate sqlinstance flags

---

pkg/resourcecreator/vault/vault.go
pkg/resourcecreator/vault/vaultcontainer.go

Kyvernopolicies krever at vi har securitycontext på alle containere

feat: add securitycontext to vault sidecars

---

pkg/resourcecreator/networkpolicy/networkpolicy.go
pkg/resourcecreator/testdata/accesspolicy_linkerd.yaml
pkg/resourcecreator/testdata/accesspolicy_nais_system.yaml
pkg/resourcecreator/testdata/accesspolicy_only_other_clusters.yaml
pkg/resourcecreator/testdata/leader_election_gcp.yaml
pkg/resourcecreator/testdata/leader_election_simple_gcp.yaml
pkg/resourcecreator/testdata/vanilla_gcp.yaml

Co-authored-by: Tommy Trøen <tommy.troen@nav.no>
Co-authored-by: sindrerh2 <sindre.rodseth.hansen@nav.no>

remove allow-all egress

---

pkg/resourcecreator/pod/pod.go
pkg/resourcecreator/testdata/naisjob/cronjob_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/job_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_cronjob_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_job_on_premises.yaml
pkg/resourcecreator/testdata/vanilla_on_premises.yaml

J-K does things he know nothing about and fixes #356

add pod anti-affinity

---

pkg/resourcecreator/networkpolicy/networkpolicy.go
pkg/resourcecreator/testdata/accesspolicy_legacy_gcp.yaml
pkg/resourcecreator/testdata/vanilla_legacy_gcp.yaml

- feat: remove cidr access to 0.0.0.0 for everything except prod-gcp in legacy
- fix: swap if statement

add condition to allow all access in prod-gcp, but not the other legacy clusters

---

go.mod
go.sum
pkg/resourcecreator/pod/helpers.go
pkg/resourcecreator/testdata/gcp_gar_toleration_with_non_gar_image.yaml
pkg/resourcecreator/testdata/vanilla_on_premises.yaml

See https://github.com/nais/features/issues/20

Remove default CPU limits, allowing users to run without CPU limit

---

.github/workflows/deploy.yaml
Dockerfile
Makefile

Tested in dev, seems to work like a charm

Do we need ca certs?

---

.gitignore
Dockerfile
Makefile
pkg/resourcecreator/google/sql/instance.go
pkg/resourcecreator/resource/operation.go
pkg/resourcecreator/testdata/gcp_database_annotate_existing_secret.yaml
pkg/synchronizer/synchronizer.go
pkg/synchronizer/synchronizer_test.go
updater/updater.go

This should trigger the password sync on every deploy, resolving the problem with password drift that happens occationally.
Fixes nais/features#33

Add correlationId to sqluser password secret on every deploy

---

charts/Chart.yaml
charts/values.yaml
pkg/generators/config.go
pkg/naiserator/config/config.go
pkg/resourcecreator/google/helpers.go
pkg/resourcecreator/google/sql/instance.go
pkg/resourcecreator/leaderelection/leaderelection.go
pkg/resourcecreator/pod/pod.go
pkg/resourcecreator/securelogs/containers.go
pkg/resourcecreator/securelogs/securelogs.go
pkg/resourcecreator/testdata/additional_kernel_capabilities_seccomp.yaml
pkg/resourcecreator/testdata/gcp_gar_toleration_with_non_gar_image.yaml
pkg/resourcecreator/testdata/naisjob/cronjob_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/job_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_cronjob_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_job_on_premises.yaml
pkg/resourcecreator/testdata/securelogs.yaml
pkg/resourcecreator/testdata/vanilla_on_premises.yaml
pkg/resourcecreator/vault/vault.go
pkg/resourcecreator/vault/vaultcontainer.go
pkg/resourcecreator/wonderwall/wonderwall.go

Vi ønsker alltid at seccomp skal være skrudd på, trenger ikke flagg for det.
fixes #393

feat: fjernet seccomp flag

---

charts/naiserator/Feature.yaml
pkg/resourcecreator/ingress/ingress.go

adding additional-gateway-mappings and mapping values for nais-ingress and nais-ingress-external

mapping values in Feature.yaml

---

pkg/resourcecreator/leaderelection/leaderelection.go

Add get pods permission to elector role so apps don't depend on other roles for leader election to work

add get pods to elector role

---

README.md
charts/naiserator/Feature.yaml
charts/naiserator/values.yaml
go.mod
go.sum
pkg/naiserator/config/config.go
pkg/resourcecreator/observability/observability.go
pkg/resourcecreator/observability/observability_test.go
pkg/resourcecreator/pod/pod.go
pkg/resourcecreator/testdata/observability_autoinstrument_enabled.yaml
pkg/resourcecreator/testdata/observability_tracing_enabled_error.yaml

OpenTelemetry Auto-Instrumentation with OpenTelementry Operator
https://opentelemetry.io/docs/concepts/instrumentation/automatic/

OpenTelemetry Auto-Instrumentation

---

Dockerfile
cmd/naiserator/main.go
pkg/scheme/listers.go
pkg/synchronizer/synchronizer_test.go

SSB har ikke Aiven CRDer, så kan ikke ha listeners for det da.

feat: Aiven listeners kun for de som har Aiven

---

charts/naiserator/Feature.yaml
charts/naiserator/values.yaml
go.mod
go.sum
pkg/generators/application.go
pkg/generators/config.go
pkg/naiserator/config/config.go
pkg/resourcecreator/azure/azureadapplication.go
pkg/resourcecreator/idporten/idporten.go
pkg/resourcecreator/login/login.go
pkg/resourcecreator/service/service.go
pkg/resourcecreator/testdata/error_not_all_idporten_azure_login_sidecar.yaml
pkg/resourcecreator/testdata/error_not_both_azure_login_sidecar.yaml
pkg/resourcecreator/testdata/error_not_both_idporten_login_sidecar.yaml
pkg/resourcecreator/testdata/login.yaml
pkg/resourcecreator/wonderwall/wonderwall.go

Depends on: https://github.com/nais/liberator/pull/234
Refs. https://github.com/nais/system/issues/61

feat: add feature toggled login stanza

---

pkg/resourcecreator/pod/pod.go
pkg/resourcecreator/testdata/env.yaml
pkg/resourcecreator/testdata/gcp_gar_toleration_with_non_gar_image.yaml
pkg/resourcecreator/testdata/naisjob/cronjob_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/job_features_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_cronjob_on_premises.yaml
pkg/resourcecreator/testdata/naisjob/vanilla_job_on_premises.yaml
pkg/resourcecreator/testdata/vanilla_on_premises.yaml

https://github.com/linkerd/linkerd-await?tab=readme-ov-file#disabling-linkerd-await-at-runtime

add linkerd_disabled env var if not enabled

---

pkg/resourcecreator/leaderelection/leaderelection.go
pkg/resourcecreator/testdata/error_leaderelection_port_conflict.yaml
pkg/resourcecreator/testdata/leader_election_elector.yaml
pkg/resourcecreator/testdata/leader_election_onprem.yaml

feat(leaderelection): use native sidecar
